language: node_js
sudo: true
node_js:
- stable
script:
- npm test
env:
  global:
  - CF_APP=personality-insights-james-demo-123213123
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=jzhang300@us.ibm.com
  - CF_SPACE=dev
  - secure: "MMrXZuEU8AFV8cG8NQvOHnLksvZ+7uGqv47WX/e3aSnllVeawfbMQXSReLKG4mqdccFQzP1U+K00ziuq3NnHN+KoQt+pS2BCYCu9VJKY/SUGvh3vpacK3p+9ho+CviCYWUnEpQhFGefv3sA2uTUUWpQsmgX/FHkumqxGTm7Xf1t9HdQlOqMlAoKt7G1qzo9pYisk9K79G6lobMXN6IQzDCm/y5ksM1sDb5G83wPWk5T4uxUcNadQeJNv4g715kqu4AawuDA0NrnG6YOnn2dcKsjBQE0zhWtYMnZZ4J3Qt0qjlxwU6wrF5UQ9RLDZ0HlAbbT6fWXcmANZFcIgQly53wGEhvpuy9kI+qJrkspZJnF5GeVf0iuLfOZLg4hGA8uXieQ/ZQ6Hy0nVDWseykvGP3gdSTpBffjKqqrcq4kSjx/AiIJtAB1oQHkkVp45pOt/tJ+KrBoloFyGXA5PK73Si1XIDQTy9+IjVFVbKtEO8eqjKK2Wqt20a3IFePI3v92RbGiirG/20XDWymGyKED9SVOhyTWvsZRZBLrwFpTFGmLB+Bf00KUg3ZMxhnEXswRirnMm0C4uOMiHZkB/wqtQdUn6M8qcb/TASDrZq538wU0HwaVirtrRp0kbnR2e2Dp/mAWJYdgDrhoGTAw/XTvS8DbH/bbnGu0EsPsggiFk6nM="
  - secure: "WrnyiA930IycJfHa7uIm+twKACVBIzIVM5hqO9V7pEaGvXcJN6QmjQ6vh8st5SDxrKPeRdZVMocDo/ilCzNtyI/jIgXUyQq+9iXAFs+6i8Xv0ZycEC8TBGl7vJWAyCqnxjFLJaIxZ4TB0W6DSbiqjSKy/IH6RSB2NMhLn7IRf72iIfGO6oClvgvYxS0yURpedUJdjM4p1w7QiH+LRg1vbxPJkhyeSC+Qd4jo0mdYIu37uithFklJfgrTJwS70shvOfoc1yr2pJC8FbxcGqkpy7Jc4/vzt3yfxKvZLgolUZlGLNvAiew7B3yzlQyR4BL/ORzG+jpFpm0fbKp+geiWihc7lnNHogtzFQLM73sJtHxYglNuEBGSQEgNhxnpWrP49g6gDio7xhJrxGg/l41NF9e0F8zvwh9KFKvNWCygh/lUdADKWZ7km2ZMqo0h1/E9yl+0G1Oll57WyQSCDi0ciW0+k5cFMDytbkuJAya1BX15cJbx6EcjQs+4oNzORMmS6rWhPeJ6pYgGW8fqx4Vr3/Fds73gxIBSScHkpvt3nqlemxdWr8nceWJc9N3WNCcVqewwEZPPV6rXhy0v2QlMbN8Re/Sp8AEwPPTruesKzXG0bV2CIpzzl/W5hJnEF3PQlRHmBaGXZNtWQcfgQggjLCAjN0DKtUfy/J2mXenNw6E="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: jzhang300/personality-insights-nodejs
  skip_cleanup: true
notifications:
  email: false
