language: node_js
sudo: true
node_js:
- stable
script:
- npm test
env:
  global:
  - CF_APP=personality-insights-james-demo-123213123
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=jzhang300@us.ibm.com
  - CF_SPACE=dev
  - secure: "IzxM7MGo8famRveArTigtIJBQdZW6/W4895xrptLs6cLJ2VQvcZRIl2PhI8SATY2LcFY86V9bMdTK3i4QAVs3TIBt2pgqhBi486DdnFqJsk84aFZxNVNZ+PIqu+LtU2xZjMeMDyTF9gOGFLAzla2gKo9PE2OjTRjHjimEcDqkDO3tJ4/WI8WMdeD1oyQVGPukmmzn3QnJuVIZ4iNQ7zxKAzMyRd8al0xPwP0JUAtGv106XPkXqHY07VXCVV0WEveFsjZUHyL47oMM19VOkFEjmeHi8geflOoAcS7uSiMOKeBZiyPCRxqeBfdIuFruYSPgncn3+Nl7omBrU0gA+bCr6v0RDmInroNMm77Zm4YWq/g0PaV5TSlnlghHJW5ttNO3bSLCBByXvyGX0oOupf5LtFmad5N6yxa19sUx7DGChUJ6189icjMInK3BSIC5Jvq1sWJvkkyHjQsj+BqTIGuuofhteg+U/wPRlQuJ8Ec3oWtl2cA7bxCbZVcs7fzIHivxvVJd5PvObpSkGp0znbhU71YwTrCkEE2uCeLE04TdQk0dptrc7GXZMiekfmekZ84//3ShcRnmMTd7XLJAWNuHnRNJ3q0OLBQGuNDLp+Wtc4Ayrk2iOFx8tAxtR7h3MO77wJrPS4pfGASBtjOmR2B0ZZUoLQ2IEgFgTsIbDh0oWI="
  - secure: "FDkXQqpz8NWh7uwtsGQWZIDPJ0ErgtrEDH/7/fjzY7TuIA4vhjI94nDaoDKeUTIzD2PSrX+wgRfcWeis9+o4Hl5DLO4sbt5/4qdftKym+Pv8bNzj4MkfICg22oYUUV4zkn7qEKrbE/cxK7DkEDClD4F547GF4zthvXy8fz4J9p7Y35mMetkyfHNy411K+m9lqiXrcVn92ESE1yZhF2EXgQhbwOqrC+QIGDEiIYCPUeP6tpBIlRxruUkpDBt3fDqvvBhoEdFSkfal6yOB4q97NLp5Yqnn13Dfv/KChyXdsgVA2W2WK156tyEYirDl6pLM+5wCCDmTKi1EHmmXRcz9DycXSIR0a5chuGRyliOCOOzsEf0CxWNKk1BSkeZIn0O02QMvwDzhQsrFZJMe/oAx0BPks6w6h04V6Cj9Hgo/jFmCWCFLG1eQWy0qQaFQNlkVvi+4PGUMSNEtmqG8A6oq6yuzepsP5JJLmhfvsbMkBD6uR/UbZEVtAifW/EuSXpO7HqFCTAPN5gZNyK+bayDkAgsyq/c1m2E15tBVWzrohjp7484tM/aefg1BVt3e7Z4PsXSSuI1iKbpnmcIxDDiXQGs0cQ4wJWmKnN0SMkKW3co5GgYqY3Yi+SRtGOfGfcbM77nztRJWWoqTjswo/f1RwimzfIPMzp5XZukfUNAMr3k="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: jzhang300/personality-insights-nodejs
  skip_cleanup: true
notifications:
  email: false
