language: node_js
sudo: true
node_js:
- stable
script:
- npm test
env:
  global:
  - CF_APP=personality-insights-james-demo-123213123
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=jzhang300@us.ibm.com
  - CF_SPACE=dev
  - secure: "Wr1vO2l4VS6xccm2Y/QJ/BRPG5eiRjNX3Oig0d1ckdFmnuM4xCoqM5OectgJOH8Ep4slg1meDJpsiF89c6lilCgA9yk+t+SLXbNAISqZ2973S/3AEkxt/ZROpAnQzecJb+okzBgwsiyfehCAvMXgEdPmsdHBl0xbcqzSM5i3xQCy0IGmOT28zR6E6r2lH5xxSwoRGvQrAA1EI9FHauavGesoKGt4uxmOyhyFBhXD1jzDkUX+Pk2BcnlKlwMScrqRFBignJpORgA0gNGZcQtMmHCststFQmuO+DxvKUyzV96wqYBt8tYGuWG/qSSE6XdPBHC6fzJnvT/zt0IAeOdOovEoo4JFEil7FA7SgQdUJDaXfqg5Cd0myStq7zzY/Ry1PF8/BITPigtLWkV0ohW1sYzuWOw07y/FL+R1qF1hB3s5orFv8SbSIe+qRCn1HZNhJI9nHkStCyBIBZNWmv5Dub0odIVNSjyYT8EHDB6Ca6Glwh5YDcVbTlgoGFY+R9W5x10gv9GQUjC5WGrYJTGk+V2mN7fin5YnvtqQKk6IIhwpbQNeygsRYw1H1ETag1zAfVI76NNx2P2SeQtxfbRmj1M2zG65jSaQO6WgfN6uw2iv2eHQMpk4pjIcEUr7vNn20y0IPt/vW/3wJV3Lq5Qwl2vVCYdtG+ClWpREl/oPga4="
  - secure: "l/7RTLgFVn0MP5b8AVvIrcUmWQ74sOYb/DNrQp0ZcZpj/O8F9oj5UrYA+RvPEClIZUEVe0Yc0Yu4FqQ8wx5oHaVYEKNYs2axVD/tl12f6gr4b+D2pfZh3SeSuzby6nNfIVrQWY3PvsGhd0PcwxKD/m1Ioqb963+n5PvKlzw/t/OPsM7g3+Kzm3LD0mU+w9JKi967hPDDoXPDRLvM/p1ZICiP6DcCLbez1/dpaHc1XjYd9XT2r9tltkbPWXnpyJj/DhIfxreFjHCV0QDiFiydHtPsmcT5YsMhTI8aKiRFRiTWYjy3LCDpp52vvIDFqsYj+kM98X0Z4tnP0ZIn9TG1EDee2i+nJdYom4muEU82ZvXMrHnrH107YJSGRp1g/QgLGCV51ZKCgejDlnERSKBTe4QBpOkh9Y4EIfb0PiFCXEg8VIaocyAiLcXe6wO+lkjXs5mRHKcBcWfvHiwvQI/r7dbYGiSmOCAEIbTqYUb7PNyyb46adWD1s17t1D8WkqTa+nYm5ezRHT9s/S4eak52qPcL3kEqY4ZIqtHButFtOWvBv7jyLz0B2HY7VkCT2VCUJ1Kcfj1xAjCHv13FwWwevZnr/4bqfgmqFM738rRQiLHnuwOnsvW+BBwwJKCIaO0xS+epXx/S98L7mncQs85Dj4w9HjS6T2iXkcZQ/W6thFo="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/personality-insights-nodejs
  skip_cleanup: true
notifications:
  email: false
